### ISSUE TITLE
Error @ CresNode at line 167

### ISSUE THREAD

**Issue by mgmatteo** [songzh96/node-red-contrib-crestron#12]
Hi, thank you for this nice node. I was testing it on my system but I get this error time to time:
```
151. Error: splusmanagerapp.exe [App 1] # 2020-11-12 06:10:29  # Module S-7.3 : CresNode at line 167: Unhandled Exception: System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
   at System.Text.StringBuilder.Remove(Int32 startIndex, Int32 length)
   at Crestron.Logos.SplusObjec152. Error: splusmanagerapp.exe [App 1] # 2020-11-12 06:10:29  # ts.CrestronString.Remove(Int32 length, Boolean bGrabLock)
   at Crestron.Logos.SplusObjects.CrestronStringExtentions.Remove(CrestronString CRString, Int32 length)
   at Crestron.Logos.SplusObjects.CrestronStringExtentions.Remove(CrestronString CRString,153. Error: splusmanagerapp.exe [App 1] # 2020-11-12 06:10:29  #  String matchStr, Int32 startPos)
   at Crestron.Logos.SplusLibrary.Functions.Remove(String matchStr, CrestronString input)
   at UserModule_CRESNODE.UserModuleClass_CRESNODE.SOCKETRX(SplusExecutionContext __context__)
   at UserModule_CRESNODE.UserMod154. Error: splusmanagerapp.exe [App 1] # 2020-11-12 06:10:29  # uleClass_CRESNODE.MYSERVER_OnSocketReceive_6(Object __Info__)
   at Amib.Threading.Internal.WorkItem.ExecuteWorkItem()
   at Amib.Threading.Internal.WorkItem.Execute()
   at Amib.Threading.SmartThreadPool.ExecuteWorkItem(WorkItem workItem)
   at Amib.155. Error: splusmanagerapp.exe [App 1] # 2020-11-12 06:10:29  # Threading.SmartThreadPool.ProcessQueuedItems()
```
I'm currently using the analog and serial signal only, no digital.
I think it is related to one of the serial inputs (nodered --> crestron) but the communication i send is just plain text..
Do you have any idea?

**Comment by songzh96** [comment]
Hi mgmatteo


What is the length of the string you sent？


Best Regards&nbsp;
Songzh



------------------ Original ------------------

**Comment by mgmatteo** [comment]
Hi Songzh,
the string I send are plain text with maximum lenght of max 50 char.
I saw that the maximum should be 1000, so I think this shoudn't be a problem.
Yust let me know if you need some more info,

BR,
Matteo

**Comment by songzh96** [comment]
I will check later&nbsp;





------------------ Original ------------------

**Comment by songzh96** [comment]
Are you using the latest version，I have fixed the string length issue before
